global:
  scrape_interval: 30s       # har 30s me scrape
  evaluation_interval: 30s
  scrape_timeout: 15s        # request timeout 15s rakha

scrape_configs:
  - job_name: "sentinelops"
    metrics_path: /metrics
    scheme: https
    static_configs:
      - targets: ["sentinelops-backend-2.onrender.com"]
