global:
  scrape_interval: 15s
  evaluation_interval: 15s
  scrape_timeout: 10s

scrape_configs:
  - job_name: "sentinelops"
    metrics_path: /metrics
    scheme: https
    static_configs:
      - targets: ["sentinelops-backend-2.onrender.com"]
